version: '3.0'
services:
  web-aff:
    image: node:18.16
    container_name: web-aff
    #restart: unless-stopped
    networks:
      - net
    ports:
      - "3000:3000"
    extra_hosts:
      - "local.aff.siam66.com:host-gateway"
    working_dir: /app/aff
    volumes:
      - ./opfe-aff-nuxt/aff:/app/aff
      - /app/web/node_modules
    command: sh -c "npm install && npm run deploy"
    environment:
      - npm_config_project=siam66    #merchant code, not sure check with FE
      - npm_config_env=stage         #value = dev/ stage / prod

networks:
  net:
   driver: bridge
